name: Test Ansible Role
on: push

jobs:
  role-test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: create pythton venv
        run: python3.8 -m venv venv

      - name: linter
        run: |
          source ./venv/bin/activate
          pip install --upgrade pip
          pip install ansible==5.10.0 ansible-lint
          ansible-lint
